/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.database.jsonc --include-runtime=false --env-interface=DatabaseEnv types/database-env.d.ts` (hash: d5d2af925c3f68aebde4bb3324980f38)
interface __BaseEnv_DatabaseEnv {
	DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../workers/database");
	}
	interface Env extends __BaseEnv_DatabaseEnv {}
}
interface DatabaseEnv extends __BaseEnv_DatabaseEnv {}
