/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.router.jsonc --include-runtime=false --env-interface=RouterEnv types/router-env.d.ts` (hash: 16ac7b1cdcc1777a3f605cbe023f7f60)
interface __BaseEnv_RouterEnv {
	APP_ENV: "development";
	DATABASE: Fetcher /* humblr-database */;
	STORAGE: Fetcher /* humblr-storage */;
	IMAGES: Fetcher /* humblr-images */;
	SSR: Fetcher /* humblr-ssr */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../workers/router");
	}
	interface Env extends __BaseEnv_RouterEnv {}
}
interface RouterEnv extends __BaseEnv_RouterEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV">> {}
}
