/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.storage.jsonc --include-runtime=false --env-interface=StorageEnv types/storage-env.d.ts` (hash: 7c0bc5093c1a8b2e7726b7b07618ba8c)
interface __BaseEnv_StorageEnv {
	BUCKET: R2Bucket;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../workers/storage");
	}
	interface Env extends __BaseEnv_StorageEnv {}
}
interface StorageEnv extends __BaseEnv_StorageEnv {}
