name: ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  cabal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Haskell toolchain
        uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.8.4"
          cabal-version: "3.12.1.0"

      - name: Build
        run: |
          cabal update
          cabal build all
      - name: Test
        run: cabal test all
      - name: Haddock
        run: cabal haddock all
